FROM python:3.11-slim

WORKDIR /app

# Для чтения docker logs нужен docker.io внутри контейнера
RUN apt-get update && apt-get install -y --no-install-recommends \
    libmagic1 \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/data

CMD ["python", "main.py"]
